# Generated by Django 5.0.1 on 2024-01-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credit',
            new_name='marks',
        ),
    ]
